//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int adminID { get; set; }
        public string userName { get; set; }
        public string passward { get; set; }
        public string confirmPassword { get; set; }
        public string email { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
