//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int roomNum { get; set; }
        public int floorNum { get; set; }
        public double price { get; set; }
        public int numberOfBed { get; set; }
        public string roomType { get; set; }
        public bool smoking { get; set; }
        public bool petFriendly { get; set; }
        public Nullable<int> gusID { get; set; }
    
        public virtual Gusets Gusets { get; set; }
    }
}
