//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int staffID { get; set; }
        public string staffName { get; set; }
        public string gender { get; set; }
        public double salary { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> deptID { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
